index:
  a: Activity
  c: Commodity
  f: Factor of production
  k: Satellite account
  n: Consumption category
  r: Country
  s: Sector
nomenclature:
  E: E
  EY: EY
  F: F
  M: M
  S: S
  U: U
  V: V
  X: X
  Y: Y
  Z: Z
  b: b
  e: e
  f: f
  g: g
  m: m
  p: p
  s: s
  u: u
  v: v
  w: L
  y: y
  z: z
